version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: http-dai-db
    restart: always
    environment:
      POSTGRES_USER: cestpolo
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: users
    ports:
      - "5123:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

